/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialLabRouteImport } from './routes/material-lab'
import { Route as NotebookCssRouteImport } from './routes/notebook-css'
import { Route as NotebookLabG2RouteImport } from './routes/notebook-lab-g2'
import { Route as NotebookLabNativeRouteImport } from './routes/notebook-lab-native'
import { Route as PaperLabRouteImport } from './routes/paper-lab'
import { Route as LabsNotebookAssetsRouteImport } from './routes/labs.notebook-assets'
import { Route as LabsPocketNotebookRouteImport } from './routes/labs.pocket-notebook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialLabRoute = MaterialLabRouteImport.update({
  id: '/material-lab',
  path: '/material-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookCssRoute = NotebookCssRouteImport.update({
  id: '/notebook-css',
  path: '/notebook-css',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookLabG2Route = NotebookLabG2RouteImport.update({
  id: '/notebook-lab-g2',
  path: '/notebook-lab-g2',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookLabNativeRoute = NotebookLabNativeRouteImport.update({
  id: '/notebook-lab-native',
  path: '/notebook-lab-native',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperLabRoute = PaperLabRouteImport.update({
  id: '/paper-lab',
  path: '/paper-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsNotebookAssetsRoute = LabsNotebookAssetsRouteImport.update({
  id: '/labs/notebook-assets',
  path: '/labs/notebook-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsPocketNotebookRoute = LabsPocketNotebookRouteImport.update({
  id: '/labs/pocket-notebook',
  path: '/labs/pocket-notebook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/material-lab': typeof MaterialLabRoute
  '/notebook-css': typeof NotebookCssRoute
  '/notebook-lab-g2': typeof NotebookLabG2Route
  '/notebook-lab-native': typeof NotebookLabNativeRoute
  '/paper-lab': typeof PaperLabRoute
  '/labs/notebook-assets': typeof LabsNotebookAssetsRoute
  '/labs/pocket-notebook': typeof LabsPocketNotebookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/material-lab': typeof MaterialLabRoute
  '/notebook-css': typeof NotebookCssRoute
  '/notebook-lab-g2': typeof NotebookLabG2Route
  '/notebook-lab-native': typeof NotebookLabNativeRoute
  '/paper-lab': typeof PaperLabRoute
  '/labs/notebook-assets': typeof LabsNotebookAssetsRoute
  '/labs/pocket-notebook': typeof LabsPocketNotebookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/material-lab': typeof MaterialLabRoute
  '/notebook-css': typeof NotebookCssRoute
  '/notebook-lab-g2': typeof NotebookLabG2Route
  '/notebook-lab-native': typeof NotebookLabNativeRoute
  '/paper-lab': typeof PaperLabRoute
  '/labs/notebook-assets': typeof LabsNotebookAssetsRoute
  '/labs/pocket-notebook': typeof LabsPocketNotebookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/material-lab'
    | '/notebook-css'
    | '/notebook-lab-g2'
    | '/notebook-lab-native'
    | '/paper-lab'
    | '/labs/notebook-assets'
    | '/labs/pocket-notebook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/material-lab'
    | '/notebook-css'
    | '/notebook-lab-g2'
    | '/notebook-lab-native'
    | '/paper-lab'
    | '/labs/notebook-assets'
    | '/labs/pocket-notebook'
  id:
    | '__root__'
    | '/'
    | '/material-lab'
    | '/notebook-css'
    | '/notebook-lab-g2'
    | '/notebook-lab-native'
    | '/paper-lab'
    | '/labs/notebook-assets'
    | '/labs/pocket-notebook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaterialLabRoute: typeof MaterialLabRoute
  NotebookCssRoute: typeof NotebookCssRoute
  NotebookLabG2Route: typeof NotebookLabG2Route
  NotebookLabNativeRoute: typeof NotebookLabNativeRoute
  PaperLabRoute: typeof PaperLabRoute
  LabsNotebookAssetsRoute: typeof LabsNotebookAssetsRoute
  LabsPocketNotebookRoute: typeof LabsPocketNotebookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-lab': {
      id: '/material-lab'
      path: '/material-lab'
      fullPath: '/material-lab'
      preLoaderRoute: typeof MaterialLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook-css': {
      id: '/notebook-css'
      path: '/notebook-css'
      fullPath: '/notebook-css'
      preLoaderRoute: typeof NotebookCssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook-lab-g2': {
      id: '/notebook-lab-g2'
      path: '/notebook-lab-g2'
      fullPath: '/notebook-lab-g2'
      preLoaderRoute: typeof NotebookLabG2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook-lab-native': {
      id: '/notebook-lab-native'
      path: '/notebook-lab-native'
      fullPath: '/notebook-lab-native'
      preLoaderRoute: typeof NotebookLabNativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper-lab': {
      id: '/paper-lab'
      path: '/paper-lab'
      fullPath: '/paper-lab'
      preLoaderRoute: typeof PaperLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/notebook-assets': {
      id: '/labs/notebook-assets'
      path: '/labs/notebook-assets'
      fullPath: '/labs/notebook-assets'
      preLoaderRoute: typeof LabsNotebookAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/pocket-notebook': {
      id: '/labs/pocket-notebook'
      path: '/labs/pocket-notebook'
      fullPath: '/labs/pocket-notebook'
      preLoaderRoute: typeof LabsPocketNotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaterialLabRoute: MaterialLabRoute,
  NotebookCssRoute: NotebookCssRoute,
  NotebookLabG2Route: NotebookLabG2Route,
  NotebookLabNativeRoute: NotebookLabNativeRoute,
  PaperLabRoute: PaperLabRoute,
  LabsNotebookAssetsRoute: LabsNotebookAssetsRoute,
  LabsPocketNotebookRoute: LabsPocketNotebookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
